version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/open-policy-agent/opa
    versions:
    - 0.26.0
    - 0.27.0
    - 0.27.1
